function Z = mapFunction(X, Y, dimension)
%MAPFUNCTION Define row distribution/density
%   Three verticle rows
%     Z = 35 * double((X > 4.5 / 7 & X < 9 / 7) | ...
%                     (X > 13.5 / 7 & X < 18 / 7) | ...
%                     (X > 22.5 / 7 & X < 27 / 7)) + 1; % z = 1 if the point is not in the one of the rows; z= 36 if it is.
    Z = 99 * double((X > 4.5 / 7 & X < 9 / 7) | ...
                    (X > 13.5 / 7 & X < 18 / 7) | ...
                    (X > 22.5 / 7 & X < 27 / 7)) + 1; % z = 1 if the point is not in the one of the rows; z= 36 if it is.

end